// <auto-generated />
using System;
using GymProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GymProject.Migrations
{
    [DbContext(typeof(AlperyurtdasGymProjectContext))]
    [Migration("20251124061007_InitialPostgreSQLMigration")]
    partial class InitialPostgreSQLMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GymProject.Models.Administrator", b =>
                {
                    b.Property<string>("AdministratorId")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("AdministratorName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AdministratorSurname")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("AdministratorId")
                        .HasName("PK_Administrator");

                    b.ToTable("Administrators");
                });

            modelBuilder.Entity("GymProject.Models.Customer", b =>
                {
                    b.Property<string>("CustomerId")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("CustomerEmail")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("CustomerIdentityNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CustomerPhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CustomerSurname")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("GymProject.Models.CustomersProgram", b =>
                {
                    b.Property<string>("CustomerProgramId")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("CustomerId")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("LeftValidity")
                        .HasColumnType("integer");

                    b.Property<string>("MovementName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProgramEndDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("ProgramStartDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("Reps")
                        .HasColumnType("integer");

                    b.Property<int?>("SetCount")
                        .HasColumnType("integer");

                    b.HasKey("CustomerProgramId");

                    b.ToTable("Customers_Program", (string)null);
                });

            modelBuilder.Entity("GymProject.Models.CustomersRegistration", b =>
                {
                    b.Property<string>("CustomerRegistrationId")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("CustomerId")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("CustomerRegistrationFinishDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("CustomerRegistrationStartDate")
                        .HasColumnType("datetime");

                    b.HasKey("CustomerRegistrationId")
                        .HasName("PK_CustomerRegistratiom");

                    b.ToTable("Customers_Registration", (string)null);
                });

            modelBuilder.Entity("GymProject.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("AdminastorId")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int?>("AdministratorBool")
                        .HasColumnType("integer");

                    b.Property<int?>("CustomerBool")
                        .HasColumnType("integer");

                    b.Property<string>("CustomerId")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.Property<string>("UserPassword")
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
