// <auto-generated />
using System;
using GymProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GymProject.Migrations
{
    [DbContext(typeof(AlperyurtdasGymProjectContext))]
    [Migration("20251124065536_AddIsPasswordChangedToCustomer")]
    partial class AddIsPasswordChangedToCustomer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GymProject.Models.BaseUser", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UserPassword")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("GymProject.Models.CustomersProgram", b =>
                {
                    b.Property<string>("CustomerProgramId")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("CustomerId")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("LeftValidity")
                        .HasColumnType("integer");

                    b.Property<string>("MovementName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProgramEndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("ProgramStartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("Reps")
                        .HasColumnType("integer");

                    b.Property<int?>("SetCount")
                        .HasColumnType("integer");

                    b.HasKey("CustomerProgramId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Customers_Program", (string)null);
                });

            modelBuilder.Entity("GymProject.Models.CustomersRegistration", b =>
                {
                    b.Property<string>("CustomerRegistrationId")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("CustomerId")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("CustomerRegistrationFinishDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("CustomerRegistrationStartDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("CustomerRegistrationId")
                        .HasName("PK_CustomerRegistratiom");

                    b.HasIndex("CustomerId");

                    b.ToTable("Customers_Registration", (string)null);
                });

            modelBuilder.Entity("GymProject.Models.Administrator", b =>
                {
                    b.HasBaseType("GymProject.Models.BaseUser");

                    b.Property<string>("AdministratorName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AdministratorSurname")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.ToTable("Administrators", (string)null);
                });

            modelBuilder.Entity("GymProject.Models.Customer", b =>
                {
                    b.HasBaseType("GymProject.Models.BaseUser");

                    b.Property<string>("CustomerEmail")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("CustomerIdentityNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CustomerPhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CustomerSurname")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsPasswordChanged")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("GymProject.Models.Trainer", b =>
                {
                    b.HasBaseType("GymProject.Models.BaseUser");

                    b.Property<string>("TrainerEmail")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("TrainerName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TrainerPhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TrainerSurname")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.ToTable("Trainers", (string)null);
                });

            modelBuilder.Entity("GymProject.Models.CustomersProgram", b =>
                {
                    b.HasOne("GymProject.Models.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GymProject.Models.CustomersRegistration", b =>
                {
                    b.HasOne("GymProject.Models.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GymProject.Models.Administrator", b =>
                {
                    b.HasOne("GymProject.Models.BaseUser", null)
                        .WithOne()
                        .HasForeignKey("GymProject.Models.Administrator", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GymProject.Models.Customer", b =>
                {
                    b.HasOne("GymProject.Models.BaseUser", null)
                        .WithOne()
                        .HasForeignKey("GymProject.Models.Customer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GymProject.Models.Trainer", b =>
                {
                    b.HasOne("GymProject.Models.BaseUser", null)
                        .WithOne()
                        .HasForeignKey("GymProject.Models.Trainer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
