// <auto-generated />
using System;
using GymProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GymProject.Migrations
{
    [DbContext(typeof(AlperyurtdasGymProjectContext))]
    [Migration("20251202085755_AddPricingPlanLanguageSupport")]
    partial class AddPricingPlanLanguageSupport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GymProject.Models.BaseUser", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UserPassword")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("GymProject.Models.ContactMessage", b =>
                {
                    b.Property<string>("ContactMessageId")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("ContactMessageId")
                        .HasName("PK_ContactMessage");

                    b.ToTable("ContactMessages", (string)null);
                });

            modelBuilder.Entity("GymProject.Models.CustomersProgram", b =>
                {
                    b.Property<string>("CustomerProgramId")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("CreatedByName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("CustomerId")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("LeftValidity")
                        .HasColumnType("integer");

                    b.Property<string>("MovementId")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("MovementName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ProgramEndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ProgramName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("ProgramStartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("Reps")
                        .HasColumnType("integer");

                    b.Property<int?>("SetCount")
                        .HasColumnType("integer");

                    b.HasKey("CustomerProgramId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("MovementId");

                    b.ToTable("Customers_Program", (string)null);
                });

            modelBuilder.Entity("GymProject.Models.CustomersRegistration", b =>
                {
                    b.Property<string>("CustomerRegistrationId")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("CustomerId")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("CustomerRegistrationFinishDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("CustomerRegistrationStartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PricingPlanId")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("CustomerRegistrationId")
                        .HasName("PK_CustomerRegistratiom");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PricingPlanId");

                    b.ToTable("Customers_Registration", (string)null);
                });

            modelBuilder.Entity("GymProject.Models.Goal", b =>
                {
                    b.Property<string>("GoalId")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal?>("CurrentValue")
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("CustomerId")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("GoalName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("GoalType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("TargetDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal?>("TargetValue")
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("TrainerId")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("GoalId")
                        .HasName("PK_Goal");

                    b.HasIndex("CustomerId");

                    b.HasIndex("TrainerId");

                    b.ToTable("Goals", (string)null);
                });

            modelBuilder.Entity("GymProject.Models.Movement", b =>
                {
                    b.Property<string>("MovementId")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("MovementDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("MovementName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MovementVideoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("MovementId")
                        .HasName("PK_Movement");

                    b.ToTable("Movements", (string)null);
                });

            modelBuilder.Entity("GymProject.Models.PricingPlan", b =>
                {
                    b.Property<string>("PricingPlanId")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("DurationInMonths")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsPopular")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Language")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("tr");

                    b.Property<string>("OriginalLanguage")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("PricingPlanId")
                        .HasName("PK_PricingPlan");

                    b.ToTable("PricingPlans", (string)null);
                });

            modelBuilder.Entity("GymProject.Models.PricingPlanFeature", b =>
                {
                    b.Property<string>("PricingPlanFeatureId")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("FeatureText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PricingPlanId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("PricingPlanId1")
                        .HasColumnType("character varying(30)");

                    b.HasKey("PricingPlanFeatureId")
                        .HasName("PK_PricingPlanFeature");

                    b.HasIndex("PricingPlanId");

                    b.HasIndex("PricingPlanId1");

                    b.ToTable("PricingPlanFeatures", (string)null);
                });

            modelBuilder.Entity("GymProject.Models.ProgramMovement", b =>
                {
                    b.Property<string>("ProgramMovementId")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("CustomerProgramId")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("MovementId")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("MovementName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("Order")
                        .HasColumnType("integer");

                    b.Property<int?>("Reps")
                        .HasColumnType("integer");

                    b.Property<int?>("SetCount")
                        .HasColumnType("integer");

                    b.HasKey("ProgramMovementId")
                        .HasName("PK_ProgramMovement");

                    b.HasIndex("CustomerProgramId");

                    b.HasIndex("MovementId");

                    b.ToTable("ProgramMovements", (string)null);
                });

            modelBuilder.Entity("GymProject.Models.PushToken", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Platform")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id")
                        .HasName("PK_PushToken");

                    b.HasIndex("CustomerId");

                    b.ToTable("PushTokens", (string)null);
                });

            modelBuilder.Entity("GymProject.Models.WorkoutLog", b =>
                {
                    b.Property<string>("WorkoutLogId")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("CustomerId")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("MovementId")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("MovementName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("Reps")
                        .HasColumnType("integer");

                    b.Property<int?>("SetCount")
                        .HasColumnType("integer");

                    b.Property<string>("TrainerId")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime?>("WorkoutDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("WorkoutDuration")
                        .HasColumnType("integer");

                    b.Property<string>("WorkoutSessionId")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("WorkoutLogId")
                        .HasName("PK_WorkoutLog");

                    b.HasIndex("CustomerId");

                    b.HasIndex("MovementId");

                    b.HasIndex("TrainerId");

                    b.HasIndex("WorkoutSessionId");

                    b.ToTable("WorkoutLogs", (string)null);
                });

            modelBuilder.Entity("GymProject.Models.WorkoutSession", b =>
                {
                    b.Property<string>("WorkoutSessionId")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("CustomerId")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("TotalDuration")
                        .HasColumnType("integer");

                    b.Property<string>("TrainerId")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("WorkoutDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("WorkoutSessionId")
                        .HasName("PK_WorkoutSession");

                    b.HasIndex("CustomerId");

                    b.HasIndex("TrainerId");

                    b.ToTable("WorkoutSessions", (string)null);
                });

            modelBuilder.Entity("GymProject.Models.Administrator", b =>
                {
                    b.HasBaseType("GymProject.Models.BaseUser");

                    b.Property<string>("AdministratorName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AdministratorSurname")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsPasswordChanged")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.ToTable("Administrators", (string)null);
                });

            modelBuilder.Entity("GymProject.Models.Customer", b =>
                {
                    b.HasBaseType("GymProject.Models.BaseUser");

                    b.Property<string>("CustomerEmail")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("CustomerIdentityNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CustomerPhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CustomerSurname")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsPasswordChanged")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("GymProject.Models.Trainer", b =>
                {
                    b.HasBaseType("GymProject.Models.BaseUser");

                    b.Property<bool>("IsPasswordChanged")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("TrainerEmail")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("TrainerName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TrainerPhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TrainerSurname")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.ToTable("Trainers", (string)null);
                });

            modelBuilder.Entity("GymProject.Models.CustomersProgram", b =>
                {
                    b.HasOne("GymProject.Models.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GymProject.Models.Movement", null)
                        .WithMany()
                        .HasForeignKey("MovementId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("GymProject.Models.CustomersRegistration", b =>
                {
                    b.HasOne("GymProject.Models.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GymProject.Models.PricingPlan", null)
                        .WithMany()
                        .HasForeignKey("PricingPlanId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("GymProject.Models.Goal", b =>
                {
                    b.HasOne("GymProject.Models.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GymProject.Models.Trainer", null)
                        .WithMany()
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("GymProject.Models.PricingPlanFeature", b =>
                {
                    b.HasOne("GymProject.Models.PricingPlan", null)
                        .WithMany("Features")
                        .HasForeignKey("PricingPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymProject.Models.PricingPlan", "PricingPlan")
                        .WithMany()
                        .HasForeignKey("PricingPlanId1");

                    b.Navigation("PricingPlan");
                });

            modelBuilder.Entity("GymProject.Models.ProgramMovement", b =>
                {
                    b.HasOne("GymProject.Models.CustomersProgram", null)
                        .WithMany()
                        .HasForeignKey("CustomerProgramId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GymProject.Models.Movement", null)
                        .WithMany()
                        .HasForeignKey("MovementId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("GymProject.Models.PushToken", b =>
                {
                    b.HasOne("GymProject.Models.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GymProject.Models.WorkoutLog", b =>
                {
                    b.HasOne("GymProject.Models.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("GymProject.Models.Movement", null)
                        .WithMany()
                        .HasForeignKey("MovementId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GymProject.Models.Trainer", null)
                        .WithMany()
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("GymProject.Models.WorkoutSession", null)
                        .WithMany()
                        .HasForeignKey("WorkoutSessionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GymProject.Models.WorkoutSession", b =>
                {
                    b.HasOne("GymProject.Models.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GymProject.Models.Trainer", null)
                        .WithMany()
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("GymProject.Models.Administrator", b =>
                {
                    b.HasOne("GymProject.Models.BaseUser", null)
                        .WithOne()
                        .HasForeignKey("GymProject.Models.Administrator", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GymProject.Models.Customer", b =>
                {
                    b.HasOne("GymProject.Models.BaseUser", null)
                        .WithOne()
                        .HasForeignKey("GymProject.Models.Customer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GymProject.Models.Trainer", b =>
                {
                    b.HasOne("GymProject.Models.BaseUser", null)
                        .WithOne()
                        .HasForeignKey("GymProject.Models.Trainer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GymProject.Models.PricingPlan", b =>
                {
                    b.Navigation("Features");
                });
#pragma warning restore 612, 618
        }
    }
}
